### ISSUE TITLE
Cannot POST to kapacitord with kapacitor-cli

### ISSUE THREAD

**Issue by melck** [influxdata/kapacitor#108]
I want to use kapacitor cli to communicate with kapacitord inside docker container but when i tried to communicate, only HTTP GET command is read by kapacitord.

How can i write on kapacitord with a distant kapacitor cli ?

Config:
Windows 7 64
Docker host: boot2docker
container base image: debian

Kapacitor config:
```toml
data_dir = "/root/.kapacitor"

[http]
  bind-address = ":9092"
  auth-enabled = false
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/kapacitor.pem"

[replay]
  dir = "/root/.kapacitor/replay"

[task]
  dir = "/root/.kapacitor/tasks"

[influxdb]
  enabled = true
  urls = ["http://influxdb:8086"]
  username = "kapacitor"
  password = "kapacitor"
  timeout = 0
  udp-buffer = 1000
  udp-read-buffer = 0

[logging]
  level = "INFO"

[stats]
  enabled = true
  stats-interval = "10s"
  database = "_kapacitor"
  retention-policy = "default"

[reporting]
  enabled = false
```
