### ISSUE TITLE
Chain topics

### ISSUE THREAD

**Issue by chopj** [influxdata/kapacitor#1260]
Is it possible to chain topics? For example to publish to topic1 and topic2?

```
var data = stream
    |from()
        .database(database)
        .measurement(measurement)
        .where(where_filter)
        .groupBy(groups)

data
    |httpOut('latest')
    |alert()
        .id(id)
        .message(message)
        .info(info)
        .warn(warn)
        .crit(crit)
        .stateChangesOnly(stateChangeInterval)
        .topic(topic1)
        .topic(topic2)


```

**Comment by atfujiwara** [comment]
I tried to do the same thing. But it did not work as I expected. Alerts were published to only the last topic.
If we want to publish to multiple topics, we should publish to intermediate topic at once.

```
...
    | alert()
      ...
      .topic('topic0')
```

and then, write handler to subscribe that topic and publish to the other ones.

```
id: topic0_handler

topics:
  - topic0

actions:
  - kind: publish
    options:
      topics:
        - topic1
        - topic2
```
