### ISSUE TITLE
[Feature Request] Kapacitor needs a way to automatically load tick scripts from a directory.

### ISSUE THREAD

**Issue by james-lawrence** [influxdata/kapacitor#1313]
having to manually invoke kapacitor for each script is pretty annoying for deployment. We should just be able to load from a directory. Main goal is to put the scripts under version control and ease of deployment.

things that may need to be thought about:

how does kapacitor know which db/rp to use?
- could implement a directory structure. scripts/{dp}/{rp}/myscript.tick

how could templates be handled?
- not sure havent used these yet.

**Comment by sputnik13** [comment]
why write a client side script that does this?  the script can iterate through whatever directory structure you have and invoke kapacitor client each time there's a change

**Comment by james-lawrence** [comment]
who says I didn't do exactly that. the problem was it was 1 additional thing I had to think about to make kapacitor operational within the infrastructure.

I mentally made a note thinking 'this is retarded, these are config files why do I need to write scripts to get a basic instance up' it felt like additional unnecessary work.

**Comment by sofuture** [comment]
Also agree this is a very helpful feature.

**Comment by goller** [comment]
I like the idea of comments specifying things like `db` and `rp`.  What about going further and making a special comment that is a command to run similar to `#!` for shell scripts or `//go:generate` for go?

Maybe like this:
```c++
// kapacitor:define my_tick -template my_tmpl -dbrp mydb.myrp -vars my_vars.json
```

**Comment by nathanielc** [comment]
@goller I like emulating the special go comments but I was thinking along different lines. More like build tags than the go:generate comments. https://golang.org/pkg/go/build/#hdr-Build_Constraints

For example your line would become:

```
// template:my_tmpl
// dbrp: mydb.myrp
// vars: my_vars.json
```

But the above doesn't really make sense because if the task being defined is sourced from a template then it doesn't have a .tick file in which to place the comments. 

Are you thinking that the template file would have a comment per task created from the template?

So an example that isn't a template would look like this:

```
// dbrp: mydb.myrp
// dbrp: anotherdb.anotherrp
```

Two other things struck me as odd:

* Your `kapacitor:define` example implies that the kapacitor CLI would be executed to actually define the task which may not be the case. But is does allow a quick bash script to be written and find the comments and run them via the CLI. So no sure which I like best.
* I would like the filename to be used as much as possible. In the `kapacitor:define` example the name of the task is explicitly specified, where I would prefer it to be sourced from the file name containing the script.

Just some thoughts....

**Comment by devth** [comment]
This feature would help when setting up TICK with automation (as opposed to by hand).

@james-lawrence care to share your script that loads your TICKs?

**Comment by jackzampolin** [comment]
@devth You can see an example of a loader script in the [`promtheus_metric_normalizer`](https://github.com/influxdata/prometheus_metric_normalizer/blob/master/define.sh).

**Comment by devth** [comment]
I added a `post-upgrade,post-install` `Job` to the Helm Chart to load TICK scripts from a directory. Looks like:

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-init
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  init.sh: |-
    #!/usr/bin/env bash
    export KAPACITOR_URL=http://kapacitor:9092
    ls -al $TICK_DIR
    kapacitor list tasks

    echo "Loading TICK files from $TICK_DIR"
    for f in ${TICK_DIR}/*.tick
    do
        name="$(basename $f)"
        name="${name/.tick/}"
        kapacitor define $name \
            -type batch \
            -dbrp telegraf.autogen \
            -tick $f
        kapacitor enable $name
    done
    echo "DONE"
    kapacitor list tasks
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-init-job
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    app: {{ template "fullname" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: OnFailure
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["bash", "/init/init.sh"]
        env:
          - name: TICK_DIR
            value: "/tick"
        volumeMounts:
        - name: alerts
          mountPath: /tick
        - name: init
          mountPath: /init
      volumes:
      - name: alerts
        configMap:
          name: {{ template "fullname" . }}-alerts
      - name: init
        configMap:
          name: {{ template "fullname" . }}-init
```

Storing the script in a ConfigMap lets me avoid having to bake/push my own Docker image. In this case I'm using the official `kapacitor` Docker image.
