### ISSUE TITLE
[Bug] Kapacitor Aggregate handler - interval option format

### ISSUE THREAD

**Issue by alexey-mk** [influxdata/kapacitor#1783]
After kapacitor upgrade from 1.3.3 to 1.4 the interval option can't parse time.Duration format from a string.

In 1.3.3 this works fine
agg.yaml
```yaml
kind: aggregate
options:
   interval: 1m
   topic: alert_log
```

In 1.4 this wont work
agg yml
```yaml
topic: agg_topic
id: agg_handler
kind: aggregate
options:
   interval: 1m
   topic: alert_log
```
I get the error
```
failed to update handler: failed to decode options into *alert.AggregateHandlerConfig: 1 error(s) decoding:
* 'interval' expected type 'time.Duration', got unconvertible type 'string'
```

So had to change to
```yaml
topic: agg_topic
id: agg_handler
kind: aggregate
options:
   interval: 60000000000
   topic: alert_log
```
