### ISSUE TITLE
[bug] Spread is not constrained to the values within a window (?)

### ISSUE THREAD

**Issue by jasonkenneth** [influxdata/kapacitor#1793]
I am working on a script to alert on too many kubernetes pod restarts within a certain window of time. I may not be using spread correctly, but I would expect for it to only use values from the defined window to do its calculation. I wrote a script that writes out spread from outside a window and from within a window, and the values inside the window seem to take all values into account. Specifically, in the output csv below, I would expect the last entry to be 0 and not 9.

[Resulting Data (csv)](https://github.com/influxdata/kapacitor/files/1700295/fakerestartsalertresults.csv.txt)

[Input Data (line protocol)](https://github.com/influxdata/kapacitor/files/1700243/restartdata.txt)

[Tick Script](https://github.com/influxdata/kapacitor/files/1700319/restartswritestats_manual.tick.txt)

Running on a kubernetes v1.7.7 cluster
Relevant TICK images:
```
  image:
    ## ref: https://hub.docker.com/r/library/kapacitor/tags/
    repository: kapacitor
    tag: 1.4.0-alpine
  image:
    ## ref: https://hub.docker.com/r/library/chronograf/tags/
    repository: chronograf
    tag: 1.4.0-alpine
  image:
    ## ref: https://hub.docker.com/r/library/influxdb/tags/
    repository: influxdb
    tag: 1.4.2-alpine
```
