### ISSUE TITLE
Kapacitor ticks generating a hash instead of their actual given name.  Inc workaround.

### ISSUE THREAD

**Issue by stephenchappo** [influxdata/kapacitor#1794]
I have the following template

```
// Compare two metrics, x & y, and alert when the ratio of them exceeds a given value.

// First metric, the dividend.
var metric_x string

// Second metric, the divisor.
var metric_y string

// Alert Threshold
var threshold string

// Service DB Type (name of service being monitored)
var dbtype string

// Message to accompany the alert, should contain an influx graph and wiki page at least.
var message string

// Location of alert history logs (if used)
var logdir = '/tmp/'

// How far back in time check looks
var duration = 1m
 
// How often check runs
var frequency = 1m

// Set topic below to this for production monitoring
var pagerduty_service = 'PAGERDUTY_TESTING'

// Service DB location that is getting monitored
var service_dbrp = '"ostrich"."autogen"."'

// How you would like the alerts to be grouped
var groupings = 'time(1m),"host","realm"'
 

// --- TEMPLATE FOLLOWS -- //
batch
    |query('SELECT mean("metric_y") AS "metric_y", mean("metric_x") as "metric_x" FROM ' + service_dbrp + dbtype + '" ')
    .period(duration)
    .every(frequency)
    .groupBy(groupings)
    .fill(0)

    |alert()
      .crit(lambda: "metric_x" / "metric_y" * 100 > threshold)
      .id('Realm: {{index .Tags "realm"}} - Hostname: {{index .Tags "host"}} / Service: ' + dbtype + '/ Metric: ' + metric_x)
      .message('{{.ID }}: {{ .Level }} - {{ index .Fields "x" }}/{{ index .Fields "x" }} = {{ index .Fields "percentage" | printf "%0.1f"}}%')
      .details(message)
      .stateChangesOnly()
      .topic(pagerduty_service)
      .log(logdir + dbtype + metric_y + 'percentage.log')
```

And a .yaml 

```
template-id: percentage_compare
dbrps:
- db: ostrich
  rp: autogen
vars:
  metric_x:
    type: string
    value: jvm_current_mem_Metaspace_max
  metric_y:
    type: string
    value: jvm_current_mem_Metaspace_used
  threshold:
    type: string
    value: '1.0'
  dbtype:
    type: string
    value: aaa_gauges+
  message:
    type: string
    value: Running out of metaspace memory.
```

I am able to define the template with no issue, however whenever I try to define the actual check I get a hash instead of the ticks' id.

```
$ kapacitor define-template percentage_compare -tick percentage_compare.tick
kapacitor define aaa_jvm_metaspace_used_task -file aaa_jvm_metaspace_used.yaml
$ kapacitor list tasks
ID                                   Type      Status    Executing Databases and Retention Policies
756ef791-9731-4d36-b532-5cc934364f82 batch     disabled  false     ["ostrich"."autogen"]
```

However I can get it to work by prefixing the .yaml with:
```
id: aaa_jvm_metaspace_used_task
template-id: jvm_metaspace_used
dbrps:
- db: ostrich
  rp: autogen
...
```

But only if I put a placeholder ID for the name of the actual tickscript.
```
$ kapacitor define   -file aaa_jvm_metaspace_used.yaml
must provide TICKscript
$ kapacitor define _ -file aaa_jvm_metaspace_used.yaml
$ kapacitor list tasks
ID                                   Type      Status    Executing Databases and Retention Policies
756ef791-9731-4d36-b532-5cc934364f82 batch     disabled  false     ["ostrich"."autogen"]
aaa_jvm_metaspace_used_task          batch     disabled  false     ["ostrich"."autogen"]
```

Which definitely does not seem to be the way this should work.

Versions of kapacitor being used:
$ kapacitor version
Kapacitor v1.4.0 (git:  fcce3ee9e6abcee5595fd61066bfc904edb1e113)
$ kapacitor -url $KAPACITOR_URL version
Kapacitor v1.4.0 (git:  fcce3ee9e6abcee5595fd61066bfc904edb1e113)
