### ISSUE TITLE
YAML to JSON conversion is breaking group by time for task definition files

### ISSUE THREAD

**Issue by cheribral** [influxdata/kapacitor#1854]
When defining a task from a YAML, it appears to be internally converted to JSON.   It is currently impossible to group by time for batch queries because the converter decides that it needs to add literal quotes around the time string.  When passing a list like:
```
  groups:
    type: list
    value:
      - type: string
        value: time(1m)
      - type: string
        value: host
      - type: string
        value: datacenter
      - type: string
        value: location
```
The query sent to influx ends up as `GROUP BY \"time(1m)\", host, datacenter, location`, which causes the query to fail.

This is using version 1.4.0
