### ISSUE TITLE
Kapacitor doesn't seem to be respecting log level from config

### ISSUE THREAD

**Issue by austinbutler** [influxdata/kapacitor#1886]
I have my logging level set to warn, but Kapacitor doesn't seem to be picking that up. I get tons of debug-level logging in `journalctl`. The only thing that seems to work is issuing `kapacitor level info`. But of course when the service restarts it's back to debug level. The CLI doesn't expose warn as a possible level.

My logging config:
```toml
[logging]
    # Destination for logs
    # Can be a path to a file or 'STDOUT', 'STDERR'.
    file = "STDOUT"
    # Logging level can be one of:
    # DEBUG, INFO, WARN, ERROR, or OFF
    level = "WARN"
```

Example message:
```
[abutler@dev ~]$ sudo journalctl -u kapacitor -f
Apr 10 19:33:36 dev kapacitord[31382]: ts=2018-04-10T19:33:36.877Z lvl=debug msg="linking subscription for cluster" service=influxdb cluster=localhost cluster=localhost
```

OS:
```
[abutler@dev ~]$ cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)
```

Kapacitor version (installed from InfluxData repo):
```
[abutler@dev ~]$ kapacitor version
Kapacitor OSS 1.4.1 (git: HEAD b05bb0f6be089d6a1a391867ad4020344ce42a53)
```
