### ISSUE TITLE
Slack workspace specification in handler doesn't work

### ISSUE THREAD

**Issue by stanislav-zaprudskiy** [influxdata/kapacitor#2054]
We have the following Slack configuration in our Kapacitor `1.5.1`:
```
[[slack]]
  enabled = true
  default = true
  url = "$KAPACITOR_SLACK_0_URL"
```
And the following handler specs:
```
id: slack-monitoring_alerts_channel
topic: slack-monitoring_alerts_channel
kind: slack
options:
  workspace: '<workspace>.slack.com'
  channel: '#alerts'
  username: 'kapacitor'
```

And with that, when alert kicks off, the following error `"workspace id not found"` shows up:
```
ts=2018-09-11T06:43:59.947Z lvl=error msg="failed to send event" service=slack handler=slack-monitoring_alerts_channel topic=slack-monitoring_alerts_channel err="workspace id not found"
```
(also tried setting log level to `"DEBUG"` but this still didn't provide a clue)

However, when the same `workspace` is specified in `kapacitor.conf`, it successfully sends alert to the channel.
```
[[slack]]
  enabled = true
  default = true
  url = "$KAPACITOR_SLACK_0_URL"
  workspace = "<workspace>.slack.com"
```
```
id: slack-monitoring_alerts_channel
topic: slack-monitoring_alerts_channel
kind: slack
options:
  channel: '#alerts'
  username: 'kapacitor'
```
