### ISSUE TITLE
disable global deadman for some scripts

### ISSUE THREAD

**Issue by LeJav** [influxdata/kapacitor#2078]
Hello,

I have deadman configured globally:
kapacitor.conf:
```toml
[deadman]
  # Configure a deadman's switch
  # Globally configure deadman's switches on all tasks.
  # NOTE: for this to be of use you must also globally configure at least one alerting method.
  ##global = false
  global = true
  # Threshold, if globally configured the alert will be triggered if the throughput in points/interval is <= threshold.
  threshold = 0.0
  # Interval, if globally configured the frequency at which to check the throughput.
  interval = "300s"
  message = "...."
```
I have a tick script using count():
```batch
var data = stream
  |from()
    .measurement('xxxxxx')
    .groupBy('xxxxxx')
    .where(lambda: "xxxx" !~ /xxxxxx/)

  data |default()
    .field('xxxx', 'xxxx')
    .tag('xxxx', '')
  |window()
    .period(period)
    .every(every)
    .align()
  |count('xxxx')
    .as('my_val')

var alert = data
  |alert()
...
```

My problem is that it may occur, and this is normal, that I have no value with the ```where``` criteria for long period. Then, count is null, and deadman sends me an alert, and also logs in log file:
```batch
error evaluating expression for level" service=kapacitor task_master=main task=xxxx node=alert5 err="left reference value \"my_val\" is missing value" level=CRITICAL
```
I would like to disable deadman for this script, and also to avoid the logs.
I have tested a lot of things without success.
Is it possible?
