### ISSUE TITLE
Group by custom eval field/tag and a list

### ISSUE THREAD

**Issue by jaw0608** [influxdata/kapacitor#2370]
Hello! 

I'm building a task template and trying to group by a custom eval field/tag as well as whatever group is passed into the template. For example, my yaml file would have a group like this:
```
...  
group:
    type: list
    value:
      - type: string
        value: 'category_1'
...
```

and I would want to be able to group like so:

```
...
|groupBy('compVal',group)
...
```

Compval is a value that is being made using eval. 

I understand that I could manually configure it within the yaml file, but it would be a pain for everyone using this template to remember to do that. 

Is there any way to accomplish this? I have not seen any documentation on combining lists.
