### ISSUE TITLE
Email Alerts Not Working From Dockerized Kapacitor

### ISSUE THREAD

**Issue by mingraham** [influxdata/kapacitor#607]
Hi,

As the last piece of a large project I am working on, I need to get email alerts from a TICKscript working, where the TICKscript is running inside a Dockerized container with Kapacitor.

In the `docker-compose.yml` file, I have the following for the Kapacitor service:

```
kapacitor:
        image: kapacitor:0.13
        environment:
            KAPACITOR_HOSTNAME: kapacitor
            KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
            KAPACITOR_SMTP_ENABLED: 'true'
            KAPACITOR_SMTP_HOST: kapacitor
            KAPACITOR_SMTP_FROM: <valid_email_address>
            KAPACITOR_SMTP_NO-VERIFY: 'true'
            KAPACITOR_SLACK_ENABLED: 'true'
            KAPACITOR_SLACK_URL: <valid_hook_url>
            KAPACITOR_SLACK_CHANNEL: <valid_channel>
        volumes:
            - ./kapacitor/tickScripts:/etc/kapacitor/tickScripts
            - ./data/kapacitor:/var/lib/kapacitor
        ports:
            - "25:25"
            - "9092:9092"
        links:
            - influxdb
```

I have the "to" field specified in the alert as `.email('<valid_email_address>')`. I am also alerting to Slack in this alert, and the Slack messages are coming through, so I am at a loss as to how to get these emails going out. In a time crunch.

Thanks,
Michael
